#!/usr/bin/env python3
"""Generate HW1's synthetic ASCII PLY and shared manifest; no external data."""

import argparse
import colorsys
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCENE_ID = "spectrum-garden"


def generate() -> tuple[bytes, bytes]:
    vertices: list[str] = []

    def point(x: float, y: float, z: float, hue: float, saturation=0.65, value=0.95):
        rgb = colorsys.hsv_to_rgb(hue % 1, saturation, value)
        color = " ".join(str(round(channel * 255)) for channel in rgb)
        vertices.append(f"{x:.6f} {y:.6f} {z:.6f} {color}")

    # A vertical warm-spectrum torus, a cool sphere, and a gently rippled floor.
    for i in range(96):
        u = 2 * math.pi * i / 96
        for j in range(32):
            v = 2 * math.pi * j / 32
            radius = 0.82 + 0.23 * math.cos(v)
            point(-1.12 + radius * math.cos(u), 0.9 + radius * math.sin(u),
                  0.23 * math.sin(v), 0.95 + 0.19 * i / 96)
    for i in range(1, 33):
        latitude = math.pi * i / 33
        for j in range(48):
            longitude = 2 * math.pi * j / 48
            point(1.12 + 0.78 * math.sin(latitude) * math.cos(longitude),
                  0.61 + 0.78 * math.cos(latitude),
                  0.78 * math.sin(latitude) * math.sin(longitude),
                  0.43 + 0.16 * i / 33, 0.72)
    for i in range(45):
        x = -2.6 + 5.2 * i / 44
        for j in range(41):
            z = -1.8 + 3.6 * j / 40
            point(x, -0.33 + 0.07 * math.sin(2 * x) * math.cos(2 * z), z,
                  0.58 + 0.16 * j / 40, 0.5, 0.65)

    header = ["ply", "format ascii 1.0",
              "comment Synthetic analytic geometry; generated by scripts/generate_sample.py",
              f"element vertex {len(vertices)}", "property float x", "property float y",
              "property float z", "property uchar red", "property uchar green",
              "property uchar blue", "end_header"]
    ply = ("\n".join(header + vertices) + "\n").encode("ascii")
    manifest = {
        "id": SCENE_ID,
        "name": "Spectrum Garden",
        "description": "A warm torus, a cool sphere, and a rippled floor. An entirely synthetic study in color, shape, and spatial annotation.",
        "format": "PLY (ASCII)",
        "point_count": len(vertices),
        "asset": f"data/{SCENE_ID}.ply",
        "size_bytes": len(ply),
        "sha256": hashlib.sha256(ply).hexdigest(),
        "generator": "scripts/generate_sample.py",
        "seed": None,
        "sampling": "Fixed analytic grids; no random sampling or external source data.",
        "coordinates": "Right-handed, Y-up; arbitrary scene units.",
    }
    return ply, (json.dumps(manifest, indent=2) + "\n").encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify without rewriting files")
    args = parser.parse_args()
    ply, manifest = generate()
    outputs = {
        ROOT / f"frontend/public/data/{SCENE_ID}.ply": ply,
        ROOT / "frontend/public/data/scene.json": manifest,
        ROOT / "backend/app/scene.json": manifest,
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                raise SystemExit(f"Out-of-date sample: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    print(f"{'Verified' if args.check else 'Generated'} {len(ply):,}-byte PLY and shared scene metadata")


if __name__ == "__main__":
    main()
